---
  - name: Create the admin tenant
    shell: keystone --os-token {{ OS_SERVICE_TOKEN }} --os-endpoint {{ OS_SERVICE_ENDPOINT }} tenant-create --name admin --description "Admin Tenant"
  - name: Create the admin user
    shell: keystone --os-token {{ OS_SERVICE_TOKEN }} --os-endpoint {{ OS_SERVICE_ENDPOINT }} user-create --name {{ openstack_admin_user }} --pass {{ openstack_admin_pass }} --email {{ openstack_admin_mail }}
   - name: Create the admin role
     shell: keystone --os-token {{ OS_SERVICE_TOKEN }} --os-endpoint {{ OS_SERVICE_ENDPOINT }} role-create --name admin
  - name: Add the admin role to the admin tenant and user
    shell: keystone --os-token {{ OS_SERVICE_TOKEN }} --os-endpoint {{ OS_SERVICE_ENDPOINT }} user-role-add --user admin --tenant admin --role admin
  - name: Create the demo tenant
    shell: keystone --os-token {{ OS_SERVICE_TOKEN }} --os-endpoint {{ OS_SERVICE_ENDPOINT }} tenant-create --name demo --description "Demo Tenant"
  - name: Create the demo user under the demo tenant
    shell: keystone --os-token {{ OS_SERVICE_TOKEN }} --os-endpoint {{ OS_SERVICE_ENDPOINT }} user-create --name {{ openstack_demo_user }} --tenant demo --pass {{ openstack_demo_pass }} --email {{ openstack_demo_mail }}
  - name: Create the service tenant
    shell: keystone --os-token {{ OS_SERVICE_TOKEN }} --os-endpoint {{ OS_SERVICE_ENDPOINT }} tenant-create --name service --description "Service Tenant"